### ISSUE TITLE
Rework search results

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/skips#9]
So that when a page is composed of multiple children, the results link to the parent
![parenting_principles_s1_family_having_fun](https://cloud.githubusercontent.com/assets/6132788/6218322/6c78e3b4-b5eb-11e4-8836-05df78e2d30d.jpg)

**Comment by luetkemj** [comment]
Good call... we could just use pagelinksto. but It would be fun to find a better programatic solution. On results find root parent id and grab that permalink. Should also be totally doable....

**Comment by luetkemj** [comment]
Done

1bd3697e2effd051a9ba865a0aa9e726a0448388
